// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ru": &dictionary{index: ruIndex, data: ruData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	":alien: Cannot load events: %v":                              23,
	":alien: Unknown command":                                     28,
	":alien: Unknown command %v":                                  19,
	":alien: Unknown event: %v":                                   75,
	":back: Back":                                                 5,
	":bell: Subscribe to comments":                                7,
	":cop: %s has deleted your comment to the \"%s\":":            67,
	":cop: %s has deleted your comment to the post in %s \"%s\":": 68,
	":cop: %s has removed a comment from %s to the post in the group %s \"%s\":": 69,
	":cop: %s has removed the post from %s from the group %s":                    72,
	":cop: %s has removed the post from %s from the group %s \"%s\":":            73,
	":cop: %s has removed your post from the group %s":                           70,
	":cop: %s has removed your post from the group %s \"%s\":":                   71,
	":e-mail: %s mentioned you in a comment to the post \"%s\":":                 44,
	":e-mail: %s mentioned you in a comment to the post in %s \"%s\":":           45,
	":e-mail: %s mentioned you in the post in %s:":                               43,
	":e-mail: %s mentioned you in the post:":                                     42,
	":e-mail: %s replyed to you in a comment to the post \"%s\":":                46,
	":e-mail: %s replyed to you in a comment to the post in %s \"%s\":":          47,
	":e-mail: New comment was posted by %s to the direct message \"%s\":":        49,
	":e-mail: New comment was posted by %s to the post \"%s\":":                  50,
	":e-mail: You received a direct message from %s:":                            48,
	":globe_with_meridians: Open comment":                                        1,
	":globe_with_meridians: Open post":                                           0,
	":key: Create token":                                                         38,
	":minus: %s request to join %s was rejected by %s":                           66,
	":minus: %s revoked admin privileges from %s in the group %s":                64,
	":minus: %s revoked subscription request to %s":                              62,
	":minus: %s revoked subscription request to you":                             61,
	":minus: %s unsubscribed from %s":                                            60,
	":minus: %s unsubscribed from your feed":                                     58,
	":no_bell: Unsubscribe from comments":                                        6,
	":no_entry_sign: Cancel":                                                     41,
	":no_entry_sign: Your request to join group %s was rejected":                 56,
	":no_entry_sign: Your subscription request to %s was rejected":               54,
	":plus: %s promoted %s to admin in the group %s":                             63,
	":plus: %s request to join %s was approved by %s":                            65,
	":plus: %s subscribed to %s":                                                 59,
	":plus: %s subscribed to your feed":                                          57,
	":raising_hand: %s sent a request to join %s that you admin":                 52,
	":raising_hand: %s sent you a subscription request":                          51,
	":shrug: Unknown command":                                                    36,
	":speech_balloon: @-Reply":                                                   3,
	":speech_balloon: Comment more":                                              8,
	":speech_balloon: Reply":                                                     2,
	":tada: %s has joined FreeFeed using your invitation":                        74,
	":tada: Comment successfully created!":                                       35,
	":warning: Cannot load event data, probably this message is too old":         14,
	":warning: Cannot load event: %v":                                            13,
	":warning: Error: %v":                                                        18,
	":warning: FreeFeed error: %v":                                               15,
	":white_check_mark: Accept":                                                  9,
	":white_check_mark: Accepted!":                                               16,
	":white_check_mark: Your request to join group %s was approved":              55,
	":white_check_mark: Your subscription request to %s was approved":            53,
	":x: Reject":                            10,
	":x: Rejected!":                         17,
	"<welcome HTML>":                        12,
	"Action is cancelled":                   20,
	"Can not send a comment without a text": 33,
	"Cannot load user information: %v":      26,
	"Checking your token...":                30,
	"Enter your comment text.":              39,
	"Enter your comment text. The comment will be prefixed with \"%s\"":                                40,
	"Error creating comment: %v":                                                                       34,
	"Hello, @%s!\nIt's all set. Now when the bot sees the update on FreeFeed, it will show it to you.": 32,
	"Language is %v now":                 11,
	"Looks like this token isn't valid.": 29,
	"More…":                              4,
	"OK, we will remove all of your data now. Use the /start command if you want to come back.":                              22,
	"Please create the access token and send it to the bot:":                                                                 37,
	"Something wrong happened: %v":                                                                                           31,
	"We already know each other. Use the /logout command if you want to delete all of your data or start over.":              21,
	"You are using this bot as %s. Use the /logout command if you want to delete all of your data or start as another user.": 27,
	"Your updates are paused now.":                                                                                           24,
	"Your updates are resumed now.":                                                                                          25,
}

var enIndex = []uint32{ // 77 elements
	// Entry 0 - 1F
	0x00000000, 0x00000021, 0x00000045, 0x0000005c,
	0x00000075, 0x0000007d, 0x00000089, 0x000000ad,
	0x000000ca, 0x000000e8, 0x00000102, 0x0000010d,
	0x00000123, 0x000002a8, 0x000002cb, 0x0000030e,
	0x0000032e, 0x0000034b, 0x00000359, 0x00000370,
	0x0000038e, 0x000003a2, 0x0000040c, 0x00000466,
	0x00000488, 0x000004a5, 0x000004c3, 0x000004e7,
	0x00000561, 0x00000579, 0x0000059c, 0x000005b3,
	// Entry 20 - 3F
	0x000005d3, 0x00000636, 0x0000065c, 0x0000067a,
	0x0000069f, 0x000006b7, 0x000006ee, 0x00000701,
	0x0000071a, 0x0000075d, 0x00000774, 0x0000079e,
	0x000007d1, 0x00000810, 0x00000858, 0x00000898,
	0x000008e1, 0x00000914, 0x0000095c, 0x0000099a,
	0x000009cf, 0x00000a10, 0x00000a53, 0x00000a93,
	0x00000ad4, 0x00000b12, 0x00000b37, 0x00000b61,
	0x00000b82, 0x00000ba8, 0x00000bda, 0x00000c0e,
	// Entry 40 - 5F
	0x00000c46, 0x00000c8b, 0x00000cc4, 0x00000cfe,
	0x00000d33, 0x00000d76, 0x00000dcb, 0x00000e02,
	0x00000e42, 0x00000e83, 0x00000ecd, 0x00000f04,
	0x00000f21,
} // Size: 332 bytes

const enData string = "" + // Size: 3873 bytes
	"\x02:globe_with_meridians: Open post\x02:globe_with_meridians: Open comm" +
	"ent\x02:speech_balloon: Reply\x02:speech_balloon: @-Reply\x02More…\x02:b" +
	"ack: Back\x02:no_bell: Unsubscribe from comments\x02:bell: Subscribe to " +
	"comments\x02:speech_balloon: Comment more\x02:white_check_mark: Accept" +
	"\x02:x: Reject\x02Language is %[1]v now\x02Hello again! This bot will he" +
	"lp you keep up-to-date with everything happening on FreeFeed. It will se" +
	"nd you <a href=\x22https://freefeed.net/filter/notifications\x22>FreeFee" +
	"d notifications</a> and you can reply to them directly in Telegram.\x0a" +
	"\x0aTo give the bot access to your notifications, you need to create a s" +
	"pecial access token. Please create it using the button below and send it" +
	" to the bot:\x02:warning: Cannot load event: %[1]v\x02:warning: Cannot l" +
	"oad event data, probably this message is too old\x02:warning: FreeFeed e" +
	"rror: %[1]v\x02:white_check_mark: Accepted!\x02:x: Rejected!\x02:warning" +
	": Error: %[1]v\x02:alien: Unknown command %[1]v\x02Action is cancelled" +
	"\x02We already know each other. Use the /logout command if you want to d" +
	"elete all of your data or start over.\x02OK, we will remove all of your " +
	"data now. Use the /start command if you want to come back.\x02:alien: Ca" +
	"nnot load events: %[1]v\x02Your updates are paused now.\x02Your updates " +
	"are resumed now.\x02Cannot load user information: %[1]v\x02You are using" +
	" this bot as %[1]s. Use the /logout command if you want to delete all of" +
	" your data or start as another user.\x02:alien: Unknown command\x02Looks" +
	" like this token isn't valid.\x02Checking your token...\x02Something wro" +
	"ng happened: %[1]v\x02Hello, @%[1]s!\x0aIt's all set. Now when the bot s" +
	"ees the update on FreeFeed, it will show it to you.\x02Can not send a co" +
	"mment without a text\x02Error creating comment: %[1]v\x02:tada: Comment " +
	"successfully created!\x02:shrug: Unknown command\x02Please create the ac" +
	"cess token and send it to the bot:\x02:key: Create token\x02Enter your c" +
	"omment text.\x02Enter your comment text. The comment will be prefixed wi" +
	"th \x22%[1]s\x22\x02:no_entry_sign: Cancel\x02:e-mail: %[1]s mentioned y" +
	"ou in the post:\x02:e-mail: %[1]s mentioned you in the post in %[2]s:" +
	"\x02:e-mail: %[1]s mentioned you in a comment to the post \x22%[2]s\x22:" +
	"\x02:e-mail: %[1]s mentioned you in a comment to the post in %[2]s \x22%" +
	"[3]s\x22:\x02:e-mail: %[1]s replied to you in a comment to the post \x22" +
	"%[2]s\x22:\x02:e-mail: %[1]s replied to you in a comment to the post in " +
	"%[2]s \x22%[3]s\x22:\x02:e-mail: You received a direct message from %[1]" +
	"s:\x02:e-mail: New comment was posted by %[1]s to the direct message " +
	"\x22%[2]s\x22:\x02:e-mail: New comment was posted by %[1]s to the post " +
	"\x22%[2]s\x22:\x02:raising_hand: %[1]s sent you a subscription request" +
	"\x02:raising_hand: %[1]s sent a request to join %[2]s that you admin\x02" +
	":white_check_mark: Your subscription request to %[1]s was approved\x02:n" +
	"o_entry_sign: Your subscription request to %[1]s was rejected\x02:white_" +
	"check_mark: Your request to join group %[1]s was approved\x02:no_entry_s" +
	"ign: Your request to join group %[1]s was rejected\x02:plus: %[1]s subsc" +
	"ribed to your feed\x02:minus: %[1]s unsubscribed from your feed\x02:plus" +
	": %[1]s subscribed to %[2]s\x02:minus: %[1]s unsubscribed from %[2]s\x02" +
	":minus: %[1]s revoked subscription request to you\x02:minus: %[1]s revok" +
	"ed subscription request to %[2]s\x02:plus: %[1]s promoted %[2]s to admin" +
	" in the group %[3]s\x02:minus: %[1]s revoked admin privileges from %[2]s" +
	" in the group %[3]s\x02:plus: %[1]s request to join %[2]s was approved b" +
	"y %[3]s\x02:minus: %[1]s request to join %[2]s was rejected by %[3]s\x02" +
	":cop: %[1]s has deleted your comment to the \x22%[2]s\x22:\x02:cop: %[1]" +
	"s has deleted your comment to the post in %[2]s \x22%[3]s\x22:\x02:cop: " +
	"%[1]s has removed a comment from %[2]s to the post in the group %[3]s " +
	"\x22%[4]s\x22:\x02:cop: %[1]s has removed your post from the group %[2]s" +
	"\x02:cop: %[1]s has removed your post from the group %[2]s \x22%[3]s\x22" +
	":\x02:cop: %[1]s has removed the post from %[2]s from the group %[3]s" +
	"\x02:cop: %[1]s has removed the post from %[2]s from the group %[3]s " +
	"\x22%[4]s\x22:\x02:tada: %[1]s has joined FreeFeed using your invitation" +
	"\x02:alien: Unknown event: %[1]v"

var ruIndex = []uint32{ // 77 elements
	// Entry 0 - 1F
	0x00000000, 0x0000002f, 0x0000006a, 0x0000008c,
	0x000000b0, 0x000000ba, 0x000000cc, 0x00000103,
	0x00000137, 0x00000160, 0x00000184, 0x00000199,
	0x000001bc, 0x00000449, 0x00000487, 0x000004ff,
	0x00000526, 0x00000549, 0x0000055f, 0x0000057d,
	0x000005b1, 0x000005d3, 0x0000067f, 0x00000704,
	0x00000749, 0x0000077b, 0x000007b4, 0x000007f5,
	0x000008d5, 0x00000903, 0x00000945, 0x0000096d,
	// Entry 20 - 3F
	0x00000997, 0x00000a45, 0x00000a8c, 0x00000acd,
	0x00000af9, 0x00000b27, 0x00000b8d, 0x00000bad,
	0x00000bec, 0x00000c6d, 0x00000c8a, 0x00000cc2,
	0x00000d10, 0x00000d6a, 0x00000dda, 0x00000e25,
	0x00000e86, 0x00000ed1, 0x00000f23, 0x00000f60,
	0x00000f9d, 0x00000ff4, 0x0000104a, 0x0000109e,
	0x00001103, 0x00001169, 0x0000119f, 0x000011db,
	0x0000121d, 0x0000124e, 0x0000128e, 0x000012e8,
	// Entry 40 - 5F
	0x0000133e, 0x000013ad, 0x0000140c, 0x0000146e,
	0x000014bf, 0x00001526, 0x0000158c, 0x000015e9,
	0x00001652, 0x000016a5, 0x00001701, 0x0000178c,
	0x000017c8,
} // Size: 332 bytes

const ruData string = "" + // Size: 6088 bytes
	"\x02:globe_with_meridians: Открыть пост\x02:globe_with_meridians: Открыт" +
	"ь коментарий\x02:speech_balloon: Ответить\x02:speech_balloon: @-Ответит" +
	"ь\x02Ещё…\x02:back: Назад\x02:no_bell: Отписаться от комментов\x02:bell" +
	": Подписаться на комменты\x02:speech_balloon: Написать ещё\x02:white_che" +
	"ck_mark: Одобрить\x02:x: Отказать\x02Ваш язык теперь %[1]v\x02Привет ещё" +
	" раз! Этот бот поможет вам быть в курсе всего, что происходит во FreeFee" +
	"d-е. Он будет присылать вам <a href=\x22https://freefeed.net/filter/noti" +
	"fications\x22>нотификации</a>, и вы сможете отвечать на них прямо в Теле" +
	"граме.\x0a\x0aДля того чтобы дать боту доступ к ваши нотификациям, вам " +
	"нужно создать специальный токен доступа. Пожалуйста, создайте его с пом" +
	"ощью кнопки ниже и отправьте боту:\x02:warning: Ошибка загрузки события" +
	": %[1]v\x02:warning: Не могу найти данные, возможно это сообщение слишко" +
	"м старое\x02:warning: Ошибка FreeFeed: %[1]v\x02:white_check_mark: Прин" +
	"ято!\x02:x: Отказано!\x02:warning: Ошибка: %[1]v\x02:alien: Неизвестная" +
	" команда %[1]v\x02Действие отменено\x02Мы с вами уже знакомы:) Используй" +
	"те команду /logout чтобы удалить все свои данные и начать заново.\x02Ва" +
	"ши данные удаляются. Используйте команду /start если захотите вернуться" +
	".\x02:alien: Не удалось загрузить события: %[1]v\x02Обновления приостано" +
	"влены\x02Обновления снова доставляются\x02Не удалось получить информаци" +
	"ю: %[1]v\x02Вы авторизованы как %[1]s. Используйте команду /logout чтоб" +
	"ы удалить все свои данные или начать работу как другой пользователь." +
	"\x02:alien: Неизвестная команда\x02Похоже что этот токен неправильный." +
	"\x02Проверяем ваш токен...\x02Что-то пошло не так: %[1]v\x02Привет, @%[1" +
	"]s!\x0aВсё готово. Теперь, когда бот увидит обновления на FreeFeed-е, он" +
	" пришлёт вам сообщение.\x02Не могу создать коментарий без текста.\x02Не " +
	"удалось создать комментарий: %[1]v\x02:tada: Комментарий создан!\x02:sh" +
	"rug: Неизвестная команда\x02Пожалуйста, создайте токен доступа и сообщит" +
	"е его боту:\x02:key: Создать токен\x02Введите текст вашего комментария:" +
	"\x02Введите текст вашего комментария. Комментарий будет начинаться с " +
	"\x22%[1]s\x22\x02:no_entry_sign: Отмена\x02:e-mail: Вас упомянули в пост" +
	"е %[1]s:\x02:e-mail: Вас упомянули в посте %[1]s в группе %[2]s:\x02:e-" +
	"mail: Вас упомянули в комментарии %[1]s к посту \x22%[2]s\x22:\x02:e-mai" +
	"l: Вас упомянули в комментарии %[1]s к посту в группе %[2]s \x22%[3]s" +
	"\x22:\x02:e-mail: Ответ %[1]s в комментарии к посту \x22%[2]s\x22:\x02:e" +
	"-mail: Ответ %[1]s в комментарии к посту в группе %[2]s \x22%[3]s\x22:" +
	"\x02:e-mail: Вы получили директ-сообщение от %[1]s:\x02:e-mail: Коммента" +
	"рий %[1]s к директ-сообщению \x22%[2]s\x22:\x02:e-mail: Комментарий %[1" +
	"]s к посту \x22%[2]s\x22:\x02:raising_hand: Запрос на подписку от %[1]s" +
	"\x02:raising_hand: Запрос на вступление в группу %[2]s от %[1]s\x02:whit" +
	"e_check_mark: Ваш запрос на подписку к %[1]s одобрен!\x02:no_entry_sign:" +
	" Ваш запрос на подписку к %[1]s отклонён\x02:white_check_mark: Ваш запро" +
	"с на всупление в группу %[1]s одобрен!\x02:white_check_mark: Ваш запрос" +
	" на всупление в группу %[1]s отклонён\x02:plus: У вас новый подписчик: %" +
	"[1]s\x02:minus: %[1]s больше не ваш подписчик:(\x02:plus: В группе %[2]s" +
	" новый подписчик: %[1]s\x02:minus: %[1]s вышел из группы %[2]s\x02:minus" +
	": Запрос подписки от %[1]s отозван\x02:minus: Запрос %[1]s на вступление" +
	" в группу %[2]s отозван\x02:plus: %[1]s сделал(а) %[2]s администратором " +
	"группы %[3]s\x02:minus: %[1]s отозвал(а) полномочия администратора груп" +
	"пы %[3]s у %[2]s\x02:plus: Запрос %[1]s на вступление в группу %[2]s од" +
	"обрен %[3]s\x02:minus: Запрос %[1]s на вступление в группу %[2]s отклон" +
	"ён %[3]s\x02:cop: Ваш комментарий был удалён %[1]s. Пост \x22%[2]s\x22:" +
	"\x02:cop: Ваш комментарий в группе %[2]s был удалён %[1]s. Пост \x22%[3]" +
	"s\x22:\x02:cop: Комментарий %[2]s был удалён %[1]s. Пост в группе %[3]s " +
	"\x22%[4]s\x22:\x02:cop: Ваш пост в группе %[2]s был удалён модератором %" +
	"[1]s\x02:cop: Ваш пост был удалён из группы %[2]s модератором %[1]s. " +
	"\x22%[3]s\x22:\x02:cop: Модератор %[1]s удалил пост %[2]s из группы %[3]" +
	"s\x02:cop: Модератор %[1]s удалил пост %[2]s из группы %[3]s \x22%[4]s" +
	"\x22:\x02:tada: По вашему приглашению зарегистрировался новый пользовате" +
	"ль FreeFeed — %[1]s!\x02:alien: Неизвестный тип события: %[1]v"

	// Total table size 10625 bytes (10KiB); checksum: AD2215E6
